namespace Haris.DataModel.Enum
{
	internal enum MySensorsStreamType
	{
		ST_FIRMWARE_CONFIG_REQUEST,
		ST_FIRMWARE_CONFIG_RESPONSE,
		ST_FIRMWARE_REQUEST,
		ST_FIRMWARE_RESPONSE,
		ST_SOUND,
		ST_IMAGE
	}
}