namespace Haris.DataModel.Enums
{
	internal enum MySensorsInternalMessageType
	{
		I_BATTERY_LEVEL,
		I_TIME,
		I_VERSION,
		I_ID_REQUEST,
		I_ID_RESPONSE,
		I_INCLUSION_MODE,
		I_CONFIG,
		I_FIND_PARENT,
		I_FIND_PARENT_RESPONSE,
		I_LOG_MESSAGE,
		I_CHILDREN,
		I_SKETCH_NAME,
		I_SKETCH_VERSION,
		I_REBOOT,
		I_GATEWAY_READY,
		I_REQUEST_SIGNING,
		I_GET_NONCE,
		I_GET_NONCE_RESPONSE
	}
}